---
- name: Test if docker is installed
  command: docker
  register: result
  ignore_errors: True

- name: Install packages to allow apt to use a repository over HTTPS
  shell: sudo apt-get install apt-transport-https ca-certificates curl software-properties-common 
  when: result|failed

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: result|failed

- name: Update the apt package index
  shell: sudo apt-get update
  when: result|failed

- name:  Set up the stable repository
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable' update_cache=yes
  when: result|failed

- name: Update the apt package index
  shell: sudo apt-get update
  when: result|failed

- name: Install the latest version of Docker CE
  shell: sudo apt-get -y install docker-ce
  when: result|failed